# Railway Nixpacks Configuration
[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["cd trend4media-backend && npm ci --production=false"]

[phases.build]
cmds = ["cd trend4media-backend && npm run build"]

[start]
cmd = "cd trend4media-backend && npm run start:prod" 