# Railway Nixpacks Configuration
[variables]
NODE_ENV = "production"
NPM_CONFIG_CACHE = "/root/.npm"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "cd trend4media-backend",
  "npm config set progress false",
  "npm config set fund false", 
  "npm config set audit false",
  "npm ci --no-audit --no-fund --prefer-offline --production=false"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "cd trend4media-backend",
  "npm run build"
]

[start]
cmd = "cd trend4media-backend && npm run start:prod" 