[build]
builder = "NIXPACKS"
buildCommand = "cd trend4media-backend && npm ci --no-audit --no-fund && npm run build"
watchPaths = ["trend4media-backend/**"]

[deploy]
startCommand = "cd trend4media-backend && npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_PROGRESS = "false" 