[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd trend4media-backend && npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 